# Generated by Django 4.1.7 on 2023-02-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategories', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(upload_to='product_type_icon')),
                ('image', models.ImageField(upload_to='product_type')),
                ('position', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
    ]
