# Generated by Django 4.1.7 on 2023-03-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='product_type',
            new_name='product_Category',
        ),
    ]
