# Generated by Django 4.1.7 on 2023-03-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_product_type_attribute_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'diet',
                'verbose_name_plural': 'diets',
            },
        ),
    ]
