# Generated by Django 4.1.7 on 2023-03-07 12:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('available_now', models.BooleanField(default=True)),
                ('discount_type', models.CharField(blank=True, choices=[('PRICE', 'Price'), ('PERCENTAGE', 'Percentage')], max_length=10, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('packing_charge', models.FloatField(default=0.0)),
                ('commission', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('attribute', models.ManyToManyField(blank=True, related_name='product_attributes', to='core.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'Region',
            },
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubRegion', models.CharField(max_length=15, unique=True)),
                ('coordinates', models.JSONField(validators=[core.models.validate_coordinates])),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
            options={
                'verbose_name': 'SubRegion',
                'verbose_name_plural': 'SubRegions',
                'db_table': 'SubRegions',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diet'),
        ),
    ]
