# Generated by Django 4.1.7 on 2023-03-08 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_region_alter_diet_diet_subregion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='Attribute',
            new_name='attribute',
        ),
        migrations.AddField(
            model_name='product',
            name='Region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AddField(
            model_name='product',
            name='SubRegion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subregion'),
        ),
    ]
