# Generated by Django 4.1.7 on 2023-03-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SubRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subregion'),
        ),
    ]
