# Generated by Django 4.1.7 on 2023-03-10 10:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_subregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SubRegion',
        ),
        migrations.AlterField(
            model_name='subregion',
            name='coordinates',
            field=models.JSONField(null=True, validators=[core.models.validate_coordinates]),
        ),
    ]
