# Generated by Django 4.1.7 on 2023-03-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_subregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
