# Generated by Django 4.2 on 2023-04-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_product_region_product_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subregion',
        ),
        migrations.CreateModel(
            name='Regioninline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ManyToManyField(to='core.region')),
                ('subregion', models.ManyToManyField(to='core.subregion')),
            ],
        ),
    ]
