# Generated by Django 4.2 on 2023-04-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_product_region_remove_product_subregion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioninline',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='core.product'),
            preserve_default=False,
        ),
    ]
