# Generated by Django 4.2 on 2023-04-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_regioninline_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regioninline',
            name='region',
        ),
        migrations.AddField(
            model_name='regioninline',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
            preserve_default=False,
        ),
    ]
