# Generated by Django 4.2 on 2023-04-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_regioninline_region_regioninline_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regioninline',
            new_name='ProductRegion',
        ),
    ]
