# Generated by Django 4.2 on 2023-04-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_regioninline_productregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AddField(
            model_name='product',
            name='SubRegion',
            field=models.ManyToManyField(to='core.subregion'),
        ),
        migrations.AlterField(
            model_name='productregion',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
