# Generated by Django 4.2 on 2023-04-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_region_product_subregion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SubRegion',
        ),
    ]
