# Generated by Django 4.2 on 2023-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_product_region_product_subregion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
